spring:
  application:
    name: pension-win-draw
  datasource:
    url: jdbc:mysql://pension-lottery-mysql:3306/pension_win_num?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
endpoint:
  health:
    show-details: always

    #defe